-- Classroom Module Schema

-- 1. Courses Table
CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  instructor TEXT NOT NULL,
  duration TEXT,
  level TEXT CHECK (level IN ('入门', '中级', '进阶', '实战')),
  rating NUMERIC(2, 1) DEFAULT 5.0,
  students_count INTEGER DEFAULT 0,
  image_url TEXT,
  price NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Course Chapters (Optional for now, but good for structure)
CREATE TABLE IF NOT EXISTS course_chapters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  "order" INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Course Lessons
CREATE TABLE IF NOT EXISTS course_lessons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id BIGINT REFERENCES course_chapters(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  video_url TEXT,
  duration TEXT,
  "order" INTEGER NOT NULL,
  is_free BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Enrollments (User purchases/signups)
CREATE TABLE IF NOT EXISTS course_enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, course_id)
);

-- RLS Policies

-- Enable RLS
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_enrollments ENABLE ROW LEVEL SECURITY;

-- Courses: Everyone can view
CREATE POLICY "Public courses are viewable by everyone" 
ON courses FOR SELECT 
USING (true);

-- Admin can manage courses (assuming admin check via public.profiles or custom claim, 
-- using the get_my_role function if available, otherwise simplified for now)
-- Note: Assuming admins have direct DB access or we add specific policies later. 
-- For now, read-only for public.

-- Enrollments: Users can view their own
CREATE POLICY "Users can view own enrollments" 
ON course_enrollments FOR SELECT 
USING (auth.uid() = user_id);

-- Insert Mock Data
INSERT INTO courses (title, description, instructor, duration, level, rating, students_count, image_url, price)
VALUES 
(
  'Midjourney 零基础入门', 
  '从注册账号到精通提示词，带你一步步掌握最强大的 AI 绘画工具。', 
  'AI 艺术研究院', 
  '2小时 30分钟', 
  '入门', 
  4.9, 
  1205, 
  'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop',
  0
),
(
  'Stable Diffusion 高级进阶', 
  '深入理解 ControlNet、LoRA 训练与局部重绘，掌控 AI 绘画的每一个细节。', 
  'TechFlow', 
  '4小时 15分钟', 
  '进阶', 
  4.8, 
  850, 
  'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop',
  199
),
(
  'Runway Gen-2 视频生成指南', 
  '探索 AI 视频生成的无限可能，学习如何用文字和图片创作电影级镜头。', 
  'Motion AI', 
  '1小时 45分钟', 
  '中级', 
  4.7, 
  620, 
  'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?q=80&w=2070&auto=format&fit=crop',
  99
),
(
  'AI 辅助商业设计实战', 
  '结合 Photoshop 与 AI 工具，提升电商海报、Logo 设计与包装设计的效率。', 
  'Design Master', 
  '3小时 20分钟', 
  '实战', 
  4.9, 
  2100, 
  'https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=2727&auto=format&fit=crop',
  299
);
