-- ==============================================================================
-- 下载历史表 (User Downloads History)
--
-- 说明：
-- 1. 记录用户的下载历史
-- 2. 包含 RLS 策略
-- ==============================================================================

CREATE TABLE IF NOT EXISTS user_downloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    video_id UUID REFERENCES videos(id) ON DELETE CASCADE NOT NULL, -- 使用 CASCADE，如果视频被删，下载记录也被删（或者 SET NULL 保留历史但无法访问）
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS
ALTER TABLE user_downloads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own downloads" ON user_downloads;
CREATE POLICY "Users can view own downloads"
ON user_downloads FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own downloads" ON user_downloads;
CREATE POLICY "Users can insert own downloads"
ON user_downloads FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 索引
CREATE INDEX IF NOT EXISTS idx_user_downloads_user_id ON user_downloads(user_id);
CREATE INDEX IF NOT EXISTS idx_user_downloads_video_id ON user_downloads(video_id);
