-- ==============================================================================
-- 综合修复脚本 (Fix All Reported Issues)
--
-- 说明：
-- 1. 修复 profiles 表缺失 created_at 字段的问题
-- 2. 修复 requests 表 user_id 外键关系缺失导致的管理后台报错
-- 3. 确保 transactions 表结构完整 (之前的报错)
-- 4. 确保 videos 表 duration 字段类型正确
-- ==============================================================================

-- 1. 修复 profiles 表缺失 created_at 字段
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

-- 2. 修复 requests 表的外键关系
-- 为了确保 Supabase 客户端能正确识别关系，我们需要明确定义外键
-- 先尝试删除可能存在的旧约束
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'requests_user_id_fkey') THEN
    ALTER TABLE public.requests DROP CONSTRAINT requests_user_id_fkey;
  END IF;
END $$;

-- 重新添加外键约束，指向 profiles 表
ALTER TABLE public.requests
ADD CONSTRAINT requests_user_id_fkey
FOREIGN KEY (user_id) REFERENCES public.profiles(id)
ON DELETE CASCADE; -- 如果用户被删，请求也删除

-- 3. 确保 transactions 表 status 字段存在 (之前的报错)
ALTER TABLE public.transactions 
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'completed';

-- 4. 确保 videos 表 duration 字段为 numeric (之前的报错 "invalid input syntax for type numeric")
-- 如果已经是 integer 或 numeric，这行不会报错
ALTER TABLE public.videos 
ALTER COLUMN duration TYPE NUMERIC USING duration::NUMERIC;

-- 5. 确保 user_downloads 表存在 (之前的修复)
CREATE TABLE IF NOT EXISTS public.user_downloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    video_id UUID REFERENCES public.videos(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS for user_downloads
ALTER TABLE public.user_downloads ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own downloads" ON public.user_downloads;
CREATE POLICY "Users can view own downloads"
ON public.user_downloads FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own downloads" ON public.user_downloads;
CREATE POLICY "Users can insert own downloads"
ON public.user_downloads FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 6. 刷新 Schema Cache 提示
-- 运行此脚本后，Supabase 会自动刷新缓存。
-- 如果问题依旧，请在 Supabase Dashboard -> Settings -> API -> 点击 "Reload schema cache"
