-- 1. Add new columns to videos table
ALTER TABLE videos ADD COLUMN IF NOT EXISTS prompt TEXT;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS ai_model TEXT;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS tags TEXT[]; -- Array of strings
ALTER TABLE videos ADD COLUMN IF NOT EXISTS downloads INTEGER DEFAULT 0;

-- 2. Create function to increment downloads safely
CREATE OR REPLACE FUNCTION increment_downloads(video_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE videos
  SET downloads = downloads + 1
  WHERE id = video_id;
END;
$$;

-- 3. Create Comments Table
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  video_id BIGINT REFERENCES videos(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for comments
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- Policies for comments
CREATE POLICY "Comments are viewable by everyone" 
ON comments FOR SELECT 
USING (true);

CREATE POLICY "Authenticated users can insert comments" 
ON comments FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own comments" 
ON comments FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own comments" 
ON comments FOR DELETE 
USING (auth.uid() = user_id);

-- 4. Add admin policy for comments (Admins can delete any comment)
CREATE POLICY "Admins can delete any comment" 
ON comments FOR DELETE 
USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() 
    AND profiles.role IN ('admin', 'super_admin')
  )
);
