-- 1. Add new columns to videos table (Idempotent)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'videos' AND column_name = 'prompt') THEN
        ALTER TABLE videos ADD COLUMN prompt TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'videos' AND column_name = 'ai_model') THEN
        ALTER TABLE videos ADD COLUMN ai_model TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'videos' AND column_name = 'tags') THEN
        ALTER TABLE videos ADD COLUMN tags TEXT[];
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'videos' AND column_name = 'downloads') THEN
        ALTER TABLE videos ADD COLUMN downloads INTEGER DEFAULT 0;
    END IF;
END $$;

-- 2. Create function to increment downloads safely (Always safe to replace)
CREATE OR REPLACE FUNCTION increment_downloads(video_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE videos
  SET downloads = downloads + 1
  WHERE id = video_id;
END;
$$;

-- 3. Create Comments Table (Idempotent)
CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  video_id BIGINT REFERENCES videos(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for comments
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

-- Policies for comments (Drop first to avoid conflicts)
DROP POLICY IF EXISTS "Comments are viewable by everyone" ON comments;
CREATE POLICY "Comments are viewable by everyone" 
ON comments FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert comments" ON comments;
CREATE POLICY "Authenticated users can insert comments" 
ON comments FOR INSERT 
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own comments" ON comments;
CREATE POLICY "Users can update their own comments" 
ON comments FOR UPDATE 
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own comments" ON comments;
CREATE POLICY "Users can delete their own comments" 
ON comments FOR DELETE 
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can delete any comment" ON comments;
CREATE POLICY "Admins can delete any comment" 
ON comments FOR DELETE 
USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() 
    AND profiles.role IN ('admin', 'super_admin')
  )
);

-- 4. Collections Module Tables
CREATE TABLE IF NOT EXISTS collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  is_public BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE collections ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Collections are viewable by everyone if public" ON collections;
CREATE POLICY "Collections are viewable by everyone if public" 
ON collections FOR SELECT 
USING (is_public = true OR auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create collections" ON collections;
CREATE POLICY "Users can create collections" 
ON collections FOR INSERT 
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own collections" ON collections;
CREATE POLICY "Users can update their own collections" 
ON collections FOR UPDATE 
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own collections" ON collections;
CREATE POLICY "Users can delete their own collections" 
ON collections FOR DELETE 
USING (auth.uid() = user_id);

-- Collection Items
CREATE TABLE IF NOT EXISTS collection_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT REFERENCES collections(id) ON DELETE CASCADE NOT NULL,
  video_id BIGINT REFERENCES videos(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(collection_id, video_id)
);

ALTER TABLE collection_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Collection items are viewable by everyone" ON collection_items;
CREATE POLICY "Collection items are viewable by everyone" 
ON collection_items FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM collections 
    WHERE collections.id = collection_items.collection_id 
    AND (collections.is_public = true OR collections.user_id = auth.uid())
  )
);

DROP POLICY IF EXISTS "Users can add items to their collections" ON collection_items;
CREATE POLICY "Users can add items to their collections" 
ON collection_items FOR INSERT 
WITH CHECK (
  EXISTS (
    SELECT 1 FROM collections 
    WHERE collections.id = collection_items.collection_id 
    AND collections.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Users can remove items from their collections" ON collection_items;
CREATE POLICY "Users can remove items from their collections" 
ON collection_items FOR DELETE 
USING (
  EXISTS (
    SELECT 1 FROM collections 
    WHERE collections.id = collection_items.collection_id 
    AND collections.user_id = auth.uid()
  )
);
