-- Fix All Missing Tables and Policies (Comprehensive Fix)
-- 1. Ensure all optional tables exist (reports, cart, orders, messages, requests, submissions)
-- 2. Fix potential schema mismatches (UUID vs BIGINT for video_id)
-- 3. Apply final RLS policies to resolve all warnings

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 0. Ensure Profile Columns Exist
-- ==========================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'is_admin') THEN
        ALTER TABLE profiles ADD COLUMN is_admin BOOLEAN DEFAULT FALSE;
    END IF;
END $$;

-- ==========================================
-- 1. Ensure Tables Exist (with correct UUID references)
-- ==========================================

-- Reports Table
CREATE TABLE IF NOT EXISTS public.reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  reporter_id UUID REFERENCES auth.users(id) NOT NULL,
  video_id UUID REFERENCES public.videos(id) ON DELETE SET NULL, -- Fixed: UUID
  comment_id BIGINT REFERENCES public.comments(id) ON DELETE SET NULL,
  reason TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'dismissed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Cart Items Table
CREATE TABLE IF NOT EXISTS public.cart_items (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) NOT NULL,
    video_id uuid REFERENCES public.videos(id) NOT NULL,
    license_type text DEFAULT 'personal',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, video_id)
);
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

-- Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) NOT NULL,
    total_amount numeric NOT NULL,
    status text DEFAULT 'completed',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Order Items Table
CREATE TABLE IF NOT EXISTS public.order_items (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    order_id uuid REFERENCES public.orders(id) NOT NULL,
    video_id uuid REFERENCES public.videos(id) NOT NULL,
    price numeric NOT NULL,
    license_type text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Messages Table
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  receiver_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Requests Table
CREATE TABLE IF NOT EXISTS public.requests (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  budget DECIMAL(10, 2) NOT NULL CHECK (budget > 0),
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'closed', 'cancelled')),
  winner_id UUID REFERENCES auth.users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.requests ENABLE ROW LEVEL SECURITY;

-- Submissions Table
CREATE TABLE IF NOT EXISTS public.submissions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  request_id UUID REFERENCES public.requests(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  video_id UUID REFERENCES public.videos(id) NOT NULL, -- Fixed: UUID
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(request_id, video_id)
);
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;


-- ==========================================
-- 2. Cleanup Old Policies
-- ==========================================
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN 
    SELECT schemaname, tablename, policyname 
    FROM pg_policies 
    WHERE tablename IN ('cart_items', 'orders', 'order_items', 'messages', 'requests', 'submissions', 'reports')
    AND schemaname = 'public'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', r.policyname, r.schemaname, r.tablename);
  END LOOP;
  
  -- Drop specific video policy if it exists
  EXECUTE 'DROP POLICY IF EXISTS "Users can upload videos" ON public.videos';
END $$;


-- ==========================================
-- 3. Apply Optimized RLS Policies
-- ==========================================

-- Cart Items
CREATE POLICY "Users can manage own cart" 
ON public.cart_items FOR ALL 
USING ((select auth.uid()) = user_id);

-- Orders
CREATE POLICY "Users can view own orders" 
ON public.orders FOR SELECT 
USING ((select auth.uid()) = user_id);

-- Order Items
CREATE POLICY "Users can view own order items" 
ON public.order_items FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.orders 
    WHERE orders.id = order_items.order_id 
    AND orders.user_id = (select auth.uid())
  )
);

-- Messages
CREATE POLICY "Users can view their own messages" 
ON public.messages FOR SELECT 
USING ((select auth.uid()) = sender_id OR (select auth.uid()) = receiver_id);

CREATE POLICY "Users can send messages" 
ON public.messages FOR INSERT 
WITH CHECK ((select auth.uid()) = sender_id);

-- Requests
CREATE POLICY "Requests are viewable by everyone" 
ON public.requests FOR SELECT 
USING (true);

CREATE POLICY "Users can insert their own requests" 
ON public.requests FOR INSERT 
WITH CHECK ((select auth.uid()) = user_id);

CREATE POLICY "Users can update their own requests" 
ON public.requests FOR UPDATE 
USING ((select auth.uid()) = user_id);

-- Submissions
CREATE POLICY "Submissions are viewable by everyone" 
ON public.submissions FOR SELECT 
USING (true);

CREATE POLICY "Users can insert their own submissions" 
ON public.submissions FOR INSERT 
WITH CHECK ((select auth.uid()) = user_id);

-- Reports
CREATE POLICY "Users can insert reports" 
ON public.reports FOR INSERT 
WITH CHECK ((select auth.uid()) = reporter_id);

CREATE POLICY "Admins can view all reports" 
ON public.reports FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = (select auth.uid()) 
    AND (role IN ('admin', 'super_admin') OR is_admin IS TRUE)
  )
);

CREATE POLICY "Admins can update reports" 
ON public.reports FOR UPDATE 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = (select auth.uid()) 
    AND (role IN ('admin', 'super_admin') OR is_admin IS TRUE)
  )
);

-- Videos (Fix Upload Policy)
CREATE POLICY "Users can upload videos" 
ON public.videos FOR INSERT 
WITH CHECK (
  (select auth.role()) = 'authenticated' 
  AND 
  user_id = (select auth.uid())
);
