-- 1. Create Recharge Requests Table
CREATE TABLE IF NOT EXISTS public.recharge_requests (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) NOT NULL,
  amount numeric NOT NULL,
  status text DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  payment_method text DEFAULT 'qrcode',
  transaction_id text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.recharge_requests ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view own recharge requests" 
ON public.recharge_requests FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own recharge requests" 
ON public.recharge_requests FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can view all recharge requests" 
ON public.recharge_requests FOR SELECT 
USING (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and (profiles.role = 'admin' or profiles.role = 'super_admin')
  )
);

CREATE POLICY "Admins can update recharge requests" 
ON public.recharge_requests FOR UPDATE 
USING (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and (profiles.role = 'admin' or profiles.role = 'super_admin')
  )
);

-- 2. Add Notifications Table (if not exists, safety check)
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  actor_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  type TEXT NOT NULL, 
  resource_id TEXT, 
  resource_type TEXT, 
  content TEXT,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- 3. Ensure Storage Buckets are Private but Accessible via Signed URLs
-- (This is usually done in Storage settings, but we can set RLS)
-- For now, we assume buckets exist.

-- 4. Fix followers_count if missed
ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS followers_count INTEGER DEFAULT 0;

-- 5. Fix video columns if missed
ALTER TABLE videos 
ADD COLUMN IF NOT EXISTS resolution TEXT, 
ADD COLUMN IF NOT EXISTS fps INTEGER, 
ADD COLUMN IF NOT EXISTS ai_model TEXT, 
ADD COLUMN IF NOT EXISTS format TEXT, 
ADD COLUMN IF NOT EXISTS size BIGINT;
