-- Create Likes table
create table likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  video_id bigint references videos(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, video_id)
);

-- Create Comments table
create table comments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  video_id bigint references videos(id) not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table likes enable row level security;
alter table comments enable row level security;

-- Policies for Likes
create policy "Likes are viewable by everyone" on likes
  for select using (true);

create policy "Users can insert their own likes" on likes
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own likes" on likes
  for delete using (auth.uid() = user_id);

-- Policies for Comments
create policy "Comments are viewable by everyone" on comments
  for select using (true);

create policy "Users can insert their own comments" on comments
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own comments" on comments
  for delete using (auth.uid() = user_id);

-- Add likes_count to videos table (optional but good for performance)
-- For now, we can just count on the fly or add a trigger later.
