-- 1. Create daily_video_stats table
CREATE TABLE IF NOT EXISTS public.daily_video_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id UUID REFERENCES public.videos(id) ON DELETE CASCADE NOT NULL,
    date DATE DEFAULT CURRENT_DATE NOT NULL,
    views INTEGER DEFAULT 0,
    downloads INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(video_id, date)
);

-- 2. Enable RLS
ALTER TABLE public.daily_video_stats ENABLE ROW LEVEL SECURITY;

-- 3. Policies
-- Owners can view their own stats
DROP POLICY IF EXISTS "Users can view stats for their own videos" ON public.daily_video_stats;
CREATE POLICY "Users can view stats for their own videos"
ON public.daily_video_stats FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.videos
        WHERE videos.id = daily_video_stats.video_id
        AND videos.user_id = auth.uid()
    )
);

-- Admins can view all
DROP POLICY IF EXISTS "Admins can view all stats" ON public.daily_video_stats;
CREATE POLICY "Admins can view all stats"
ON public.daily_video_stats FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.profiles
        WHERE profiles.id = auth.uid()
        AND profiles.role IN ('admin', 'super_admin')
    )
);

-- 4. Update increment_views function to also update daily stats
CREATE OR REPLACE FUNCTION public.increment_views(video_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Update total views
  UPDATE public.videos
  SET views = COALESCE(views, 0) + 1
  WHERE id = video_id;

  -- Upsert daily stats
  INSERT INTO public.daily_video_stats (video_id, date, views)
  VALUES (video_id, CURRENT_DATE, 1)
  ON CONFLICT (video_id, date)
  DO UPDATE SET views = daily_video_stats.views + 1;
END;
$$;

-- 5. Update increment_downloads function to also update daily stats
CREATE OR REPLACE FUNCTION public.increment_downloads(video_id UUID)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Update total downloads
  UPDATE public.videos
  SET downloads = COALESCE(downloads, 0) + 1
  WHERE id = video_id;

  -- Upsert daily stats
  INSERT INTO public.daily_video_stats (video_id, date, downloads)
  VALUES (video_id, CURRENT_DATE, 1)
  ON CONFLICT (video_id, date)
  DO UPDATE SET downloads = daily_video_stats.downloads + 1;
END;
$$;
